[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "ll"

#[[session]]
#name = "htb ğŸ±"
#path = "~/projects/htb/"
#startup_command = "tmuxinator start htb"
#preview_command = "bat --color=always ~/projects/kali-pod/Containerfile"
